// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buvnifpsqwvzqndcwdrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dm5pZnBzcXd2enFuZGN3ZHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODc3MDgsImV4cCI6MjA1NzM2MzcwOH0.BMi90LvxckYKvyot0QBH8oDfBC8FF5v9aSHUD_ttjtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});